version: '3.1'

services:
  fullstejk:
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
    user: ${USR_UID}:${USR_GID}
    image:  fullstejk-application:latest
    container_name: fullstejk-application
    restart: on-failure:3
    read_only: true
    tmpfs:
      - /tmp
    ports:
      - 8085:8085
    networks:
      - fullstejk_network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: "curl --fail http://localhost:8085/ || exit 1"
      interval: 5s
      timeout: 3s
      retries: 3
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
networks:
  fullstejk_network:


