name: gha_basic:GitHub Action flow to Docker hub

on:
  #  workflow_dispatch:
  push:
    branches: [main]
jobs:
  build-push-images:
    name: Budowa i publikacja obrazw na repozytorium
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: |
            798483003/fullstejk:multiplatform
